//! Compare `valverig-nam` against output produced by the actual C++ reference.
//!
//! `assets/vectors/` holds `(input, output)` pairs generated by running
//! `NeuralAmpModelerCore` itself; see `README.md` and
//! `tools/regen-assets.sh`. Each case names a model, a PRNG seed and a block
//! schedule; the schedules are chosen to straddle ring-buffer wraps and to
//! include single-sample calls.
//!
//! `assets/expectations.txt` records, per case, whether the reference's kernel
//! is order-equivalent to ours (`exact`) or not (`approx`, with the measured
//! bound). See the crate README for why that distinction exists and why it is
//! not a fudge factor: the C++ reference is not bit-stable against *itself*
//! across its own supported build configurations, and this file pins exactly
//! where our arithmetic lands relative to it.

mod common;

use common::read_f64;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use valverig_nam::loader::Model;

fn assets_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("assets")
}

/// The `.meta.json` sidecar `tools/gen_vectors.cpp` writes next to each vector.
#[derive(Deserialize)]
struct Meta {
    in_channels: usize,
    out_channels: usize,
    num_samples: usize,
    sample_rate: f64,
    #[serde(default = "prewarm_default")]
    prewarm: bool,
    /// What the reference's `GetPrewarmSamples` returned for the model.
    prewarm_samples: usize,
    max_block: usize,
    schedule: Vec<usize>,
    /// The reference's `GetLoudness`, when the file states one, to six
    /// significant digits.
    loudness: Option<f64>,
}

fn prewarm_default() -> bool {
    true
}

/// One case: its sidecar plus the input and reference output blobs.
struct Case {
    name: String,
    model: String,
    meta: Meta,
    input: Vec<f64>,
    expected: Vec<f64>,
}

fn load_cases() -> Vec<Case> {
    let dir = assets_dir().join("vectors");
    let mut cases = Vec::new();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return cases;
    };
    let mut names: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let n = e.file_name().to_string_lossy().into_owned();
            n.strip_suffix(".meta.json").map(str::to_owned)
        })
        .collect();
    names.sort();

    for name in names {
        let meta = std::fs::read_to_string(dir.join(format!("{name}.meta.json"))).unwrap();
        let meta: Meta =
            serde_json::from_str(&meta).unwrap_or_else(|e| panic!("{name}.meta.json: {e}"));
        // "<model>__<variant>"
        let model = name.split("__").next().unwrap().to_owned();
        cases.push(Case {
            input: read_f64(&dir.join(format!("{name}.in.f64"))),
            expected: read_f64(&dir.join(format!("{name}.out.f64"))),
            meta,
            model,
            name,
        });
    }
    cases
}

/// Run one case, returning our output per channel.
fn run(case: &Case) -> Result<Vec<Vec<f64>>, valverig_nam::error::Error> {
    let path = assets_dir()
        .join("models")
        .join(format!("{}.nam", case.model));
    let Meta {
        in_channels,
        out_channels,
        num_samples: n,
        sample_rate,
        prewarm,
        max_block,
        ..
    } = case.meta;
    let mut model = Model::from_file(&path)?;
    assert_eq!(model.in_channels(), in_channels, "{}", case.name);
    assert_eq!(model.out_channels(), out_channels, "{}", case.name);
    // The sidecar's loudness is what the reference's `GetLoudness` returned,
    // written by an ostream at its default six significant digits.
    match (model.metadata.loudness, case.meta.loudness) {
        (None, None) => {}
        (Some(ours), Some(theirs)) => assert!(
            (ours - theirs).abs() <= 1e-5 * theirs.abs().max(1.0),
            "{}: loudness {ours} vs the reference's {theirs}",
            case.name
        ),
        (ours, theirs) => panic!(
            "{}: loudness {ours:?} vs the reference's {theirs:?}",
            case.name
        ),
    }

    // `<model>__slim0_33` means the generator passed `--slim 0.33`. Only the
    // `SlimmableContainer` models carry these cases: a slimmable WaveNet is
    // run at full width and has none. The size is set before `reset`, as the
    // reference's `render` tool does, because selecting a child settles it and
    // it would otherwise be prewarmed at the wrong size.
    if let Some(tag) = case.name.split("__slim").nth(1) {
        let value: f64 = tag.replace('_', ".").parse().expect("slim tag");
        model.set_slimmable_size(value)?;
    }
    // The reference reports the active child's figure for a container, so
    // the comparison happens after the size is selected. For a slimmable
    // WaveNet the reference's `SlimmableWavenet::GetPrewarmSamples` returns
    // 0 while its `Reset` resets the inner WaveNet, which prewarms with that
    // WaveNet's own count; this crate reports the count it actually settles
    // with, and the vectors themselves hold the two to the same behaviour.
    if is_slimmable_wavenet(&path) {
        assert_eq!(
            case.meta.prewarm_samples, 0,
            "{}: the reference reports 0 here",
            case.name
        );
        assert!(
            model.prewarm_samples() > 0,
            "{}: prewarm samples",
            case.name
        );
    } else {
        assert_eq!(
            model.prewarm_samples(),
            case.meta.prewarm_samples,
            "{}: prewarm samples",
            case.name
        );
    }
    model.set_prewarm_on_reset(prewarm);
    model.reset(sample_rate, max_block);

    // The reference's boundary is `double`, but its arithmetic is `float`: the
    // input is narrowed on the way in and the output widened on the way out.
    // Narrowing here reproduces that exactly.
    let input: Vec<Vec<f32>> = (0..in_channels)
        .map(|c| {
            case.input[c * n..(c + 1) * n]
                .iter()
                .map(|&x| x as f32)
                .collect()
        })
        .collect();
    let mut got = vec![vec![0.0f32; n]; out_channels];

    let mut in_buf = vec![vec![0.0f32; max_block]; in_channels];
    let mut out_buf = vec![vec![0.0f32; max_block]; out_channels];

    let mut pos = 0usize;
    let mut si = 0usize;
    while pos < n {
        let mut b = case.meta.schedule[si % case.meta.schedule.len()];
        si += 1;
        b = b.min(n - pos);
        if b == 0 {
            break;
        }
        for c in 0..in_channels {
            in_buf[c][..b].copy_from_slice(&input[c][pos..pos + b]);
        }
        {
            let ins: Vec<&[f32]> = in_buf.iter().map(|v| v.as_slice()).collect();
            let mut outs: Vec<&mut [f32]> = out_buf.iter_mut().map(|v| v.as_mut_slice()).collect();
            model.process(&ins, &mut outs, b);
        }
        for c in 0..out_channels {
            got[c][pos..pos + b].copy_from_slice(&out_buf[c][..b]);
        }
        pos += b;
    }

    Ok(got
        .into_iter()
        .map(|v| v.into_iter().map(|x| x as f64).collect())
        .collect())
}

/// Whether the model file is a WaveNet with a `slimmable` block on any layer
/// array: `config_is_slimmable_wavenet` in `NAM/wavenet/model.cpp`.
fn is_slimmable_wavenet(path: &Path) -> bool {
    let v: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    v["architecture"] == "WaveNet"
        && v["config"]["layers"].as_array().is_some_and(|ls| {
            ls.iter()
                .any(|l| l.get("slimmable").is_some_and(|s| s.is_object()))
        })
}

/// Difference summary between our output and the reference's.
struct Diff {
    exact: bool,
    max_abs: f64,
    max_rel: f64,
    first_bad: Option<usize>,
}

fn compare(case: &Case, got: &[Vec<f64>]) -> Diff {
    let n = case.meta.num_samples;
    let scale = case
        .expected
        .iter()
        .fold(0.0f64, |m, x| m.max(x.abs()))
        .max(f64::MIN_POSITIVE);
    let mut d = Diff {
        exact: true,
        max_abs: 0.0,
        max_rel: 0.0,
        first_bad: None,
    };
    for (c, chan) in got.iter().enumerate().take(case.meta.out_channels) {
        for (i, &a) in chan.iter().enumerate().take(n) {
            let b = case.expected[c * n + i];
            if a.to_bits() != b.to_bits() {
                if d.exact {
                    d.first_bad = Some(c * n + i);
                }
                d.exact = false;
                let e = (a - b).abs();
                d.max_abs = d.max_abs.max(e);
                d.max_rel = d.max_rel.max(e / scale);
            }
        }
    }
    d
}

/// The reference's own build-to-build disagreement, per case, as measured by
/// `tools/regen-assets.sh` across four configurations it ships and supports.
fn reference_spread() -> BTreeMap<String, f64> {
    let p = assets_dir().join("reference-spread.txt");
    let Ok(text) = std::fs::read_to_string(p) else {
        return BTreeMap::new();
    };
    text.lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|l| !l.is_empty())
        .filter_map(|l| l.split_once(char::is_whitespace))
        .filter_map(|(k, v)| v.trim().parse().ok().map(|f| (k.to_owned(), f)))
        .collect()
}

fn expectations() -> BTreeMap<String, String> {
    let p = assets_dir().join("expectations.txt");
    let Ok(text) = std::fs::read_to_string(p) else {
        return BTreeMap::new();
    };
    text.lines()
        // Everything from a '#' is a comment, including the measured values
        // the recorder writes alongside each bound.
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|l| !l.is_empty())
        .filter_map(|l| l.split_once(char::is_whitespace))
        .map(|(k, v)| (k.to_owned(), v.trim().to_owned()))
        .collect()
}

#[test]
fn matches_the_cpp_reference_within_the_recorded_expectations() {
    let cases = load_cases();
    assert!(
        !cases.is_empty(),
        "no reference vectors found; run tools/regen-assets.sh"
    );
    let expect = expectations();
    assert!(
        !expect.is_empty(),
        "assets/expectations.txt is missing; run `cargo test --test reference -- --ignored record_expectations`"
    );
    let spread = reference_spread();
    let mut failures = Vec::new();
    let mut skipped = Vec::new();

    for case in &cases {
        let Some(want) = expect.get(&case.name) else {
            failures.push(format!(
                "{}: no entry in assets/expectations.txt",
                case.name
            ));
            continue;
        };
        if want == "unsupported" {
            skipped.push(case.name.clone());
            continue;
        }

        let got = match run(case) {
            Ok(g) => g,
            Err(e) => {
                failures.push(format!("{}: failed to run: {e}", case.name));
                continue;
            }
        };
        let d = compare(case, &got);

        if let Some(bound) = want.strip_prefix("approx:") {
            let bound: f64 = bound.trim().parse().unwrap_or_else(|_| {
                panic!(
                    "{}: malformed bound {want:?} in expectations.txt",
                    case.name
                )
            });
            // The bounds were recorded on arm64 macOS against a reference
            // built there, and the tight ones are tight because that libm's
            // tanhf and expf are the reference's. Elsewhere the libm differs
            // in the last bit, so a case is held to the larger of its bound
            // and the reference's own build-to-build spread instead.
            let native = cfg!(all(target_arch = "aarch64", target_os = "macos"));
            let limit = if native {
                bound
            } else {
                bound.max(spread.get(&case.name).copied().unwrap_or(0.0))
            };
            if d.max_rel > limit {
                failures.push(format!(
                    "{}: relative error {:.3e} exceeds recorded bound {:.3e}{}",
                    case.name,
                    d.max_rel,
                    bound,
                    if native {
                        String::new()
                    } else {
                        format!(" (and the reference's own spread, {:.3e})", limit)
                    }
                ));
            }
        } else {
            failures.push(format!("{}: unrecognised expectation {want:?}", case.name));
        }
    }

    if !skipped.is_empty() {
        eprintln!(
            "{} case(s) marked unsupported and skipped:\n  {}",
            skipped.len(),
            skipped.join("\n  ")
        );
    }
    assert!(
        failures.is_empty(),
        "{} case(s) failed:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Where we differ from the reference, we differ by about as much as the
/// reference differs from *itself*.
///
/// `assets/vectors/*.out.f64` comes from one specific build of the C++
/// reference. That build is not privileged: the same source compiled with
/// vectorised Eigen, or with `-Ofast`, or with the A2 fast path enabled,
/// produces different bits, up to about 4e-6 relative on these models, as
/// `assets/reference-spread.txt` records. So "bit-exact against the C++
/// reference" is only a well-posed target relative to a pinned configuration.
///
/// This test states the claim that survives that, and states it as measured
/// rather than as hoped. Across every case the ratio of our deviation to the
/// reference's own spread runs from 0.00x to 1.04x: the same size, and at
/// present just inside their hull. That is a consequence of `kernels::macc`
/// fusing, which moves our arithmetic towards the reference's own release
/// build; it is not a property to rely on. Our reduction order is one more
/// valid ordering alongside the reference's four, not a closer or a worse
/// one, so there is no reason it must fall inside their hull.
///
/// The bound is therefore twice the measured spread: tight enough that an
/// order-of-magnitude regression fails immediately, loose enough not to
/// depend on landing strictly inside the hull.
#[test]
fn deviation_stays_inside_the_references_own_build_to_build_spread() {
    let cases = load_cases();
    let expect = expectations();
    let spread = reference_spread();
    assert!(
        !spread.is_empty(),
        "assets/reference-spread.txt is missing; run tools/regen-assets.sh"
    );

    // Justified by measurement, not by taste: see the doc comment.
    const SPREAD_MULTIPLE: f64 = 2.0;

    let mut checked = 0usize;
    let mut worst_ratio = 0.0f64;
    let mut failures = Vec::new();
    for case in &cases {
        if expect.get(&case.name).map(String::as_str) == Some("unsupported") {
            continue;
        }
        let Some(&spread_here) = spread.get(&case.name) else {
            failures.push(format!(
                "{}: no entry in assets/reference-spread.txt",
                case.name
            ));
            continue;
        };
        let Ok(got) = run(case) else { continue };
        let d = compare(case, &got);
        checked += 1;
        if spread_here > 0.0 {
            worst_ratio = worst_ratio.max(d.max_rel / spread_here);
        }
        if d.max_rel > SPREAD_MULTIPLE * spread_here {
            failures.push(format!(
                "{}: deviation {:.3e} is {:.2}x the reference's own spread of {:.3e}",
                case.name,
                d.max_rel,
                d.max_rel / spread_here,
                spread_here
            ));
        }
    }
    assert!(checked > 0, "no supported cases were checked");
    assert!(failures.is_empty(), "{}", failures.join("\n"));
    eprintln!(
        "{checked} cases; worst deviation is {worst_ratio:.2}x the reference's own \
         build-to-build spread"
    );
}
/// Regenerate `assets/expectations.txt` from the current implementation.
///
/// Ignored by default: it *records* behaviour rather than checking it. Run it
/// deliberately, read the diff, and commit the result only when you understand
/// why anything moved.
///
///     cargo test --test reference -- --ignored --nocapture record_expectations
#[test]
#[ignore = "records expectations rather than checking them"]
fn record_expectations() {
    /// Floor for a case that lands bit-identical, so its bound is a real
    /// number rather than zero. One part in 10^9 is far below anything the
    /// arithmetic can drift by without something being wrong.
    const RECORD_FLOOR: f64 = 1e-9;

    let cases = load_cases();
    assert!(
        !cases.is_empty(),
        "no reference vectors found; run tools/regen-assets.sh"
    );
    let mut lines = vec![
        "# Generated by `cargo test --test reference -- --ignored record_expectations`."
            .to_string(),
        "# One line per case:".to_string(),
        "#   approx:<r>   our output is within <r> of the C++ reference's,".to_string(),
        "#                relative to the signal peak".to_string(),
        "#   unsupported  this crate cannot load the model yet".to_string(),
        "# A case that currently lands bit-identical is still recorded as a bound;".to_string(),
        "# see README.md, \"How close, and to what\".".to_string(),
        String::new(),
    ];
    let mut n_approx = 0;
    let mut n_unsup = 0;
    let mut n_exact = 0;
    for case in &cases {
        let line = match run(case) {
            Err(_) => {
                n_unsup += 1;
                format!("{} unsupported", case.name)
            }
            Ok(got) => {
                let d = compare(case, &got);
                n_approx += 1;
                if d.exact {
                    n_exact += 1;
                }
                // Every case gets a bound, the ones that happen to land
                // bit-identical included: that they do is a property of one
                // model's arithmetic on one target, not something to hold the
                // crate to. Headroom over the measured value keeps
                // noise-level jitter from churning the file, and what was
                // actually measured is recorded beside it.
                let bound = (d.max_rel * 4.0).max(RECORD_FLOOR);
                let spread = reference_spread()
                    .get(&case.name)
                    .copied()
                    .unwrap_or(f64::NAN);
                format!(
                    "{} approx:{:.1e}   # measured {:.3e} rel, {:.3e} abs, {:.2}x the reference's own spread",
                    case.name,
                    bound,
                    d.max_rel,
                    d.max_abs,
                    d.max_rel / spread
                )
            }
        };
        lines.push(line);
    }
    let path = assets_dir().join("expectations.txt");
    std::fs::write(&path, lines.join("\n") + "\n").unwrap();
    eprintln!(
        "wrote {} ({} bounds, {} of them currently bit-identical, {} unsupported)",
        path.display(),
        n_approx,
        n_exact,
        n_unsup
    );
}
